### ISSUE TITLE
Disappear time wrong

### ISSUE THREAD

**Issue by dikkedeur** [eugenio412/PogomBOT#14]
I installed the bot, great job for it, works great.
However..

the bot tells me that for example weepinbell 
disappear at 51min.

my current time is 12:38 so i assume it means disappear at 12:51 not that it disappear in 51 minutes.
so in short its missing the HOURS before the minutes time.

![schermafbeelding 2016-08-19 om 12 43 28](https://cloud.githubusercontent.com/assets/11842306/17807405/9200d86e-660a-11e6-906d-011866ff42d5.png)

**Comment by eugenio412** [comment]
yes, sorry, a small typo, I'll correct it right now

*edit: DONE

**Comment by dikkedeur** [comment]
great, will do a pull 👍

**Comment by dikkedeur** [comment]
did a test and it is still saying Disappear at min 29..
so i dont think the fix did the trick.

**Comment by eugenio412** [comment]
Oh, but that's how it is supposed to work, usually VPS and servers are in different timezones and a pokemon never stays more that 15 min, to I decided to show only the minute it will disappear.

**Comment by dikkedeur** [comment]
but then again you mean show the time it will disappear like 4 minutes or 14 minutes ( most dont last 15 minutes i think max spawntime is 15 min )
but now it shows the min of the hour it will despawn..
so when it despawns at 12:49 it will say disappear at 49, i just miss the hours in the text or say it will disappear at x or y minutes..
2 different things ^^

**Comment by Korzakov** [comment]
I agree with you on that dikkedeur.

Maybe a text like this:

Disappears at 19:50:46 (11m44s) 

I'd like to see the actual time the pokemon disappears, because otherwise you have to find out for yourself how long it it is still there by comparing the time left and time of sending the message.

If the time is not correct due to timezones, maybe you could make an offset property for the hour difference in the config? Don't know if thats possible, just an idea.

**Comment by Unknown66** [comment]
Okay the problem with this is the timezone thats why I didnt added the complete timestamp.
If I've got the time I will fix it.
