### ISSUE TITLE
Setting multiple categories

### ISSUE THREAD

**Issue by SM411** [eugenio412/PogomBOT#3]
Hi,
If I would like to set notifications for both very rare and ultra rare, how should I procede? I tried to read the script, and if I read correctly it should be done by writing this:
`/setbyrarity 4
/setbyrarity 5`

But I'm not 100 % sure that this works or if the last command overwrites the first, or the first commands also include the effect of the second command (4 and more rare). 

Btw, why is Snorlax only rare (3) ?

**Comment by eugenio412** [comment]
They just pile up, so doing both will notify you for rarity 4 and 5. But I should write it more carefully in the readme. If you like you could pull a request and I'll merge it. Or otherwise I'll do it by myself tomorrow.
Oh, and I know, it's crazy but snorlax is not considered ultra rare, but you can add him with /set 3 on the top of the other notifications

**Comment by eugenio412** [comment]
Oh, and I know, it's crazy but snorlax is not considered ultra rare, but you can add him with /set 3 on the top of the other notifications

**Comment by Unknown66** [comment]
I added this in #10 with the ability to add other pokemon too.
