### ISSUE TITLE
IV based notifications

### ISSUE THREAD

**Issue by eugenio412** [eugenio412/PogomBOT#53]
as said in title, please add yourself as Assignee if you are working on it

**Comment by Unknown66** [comment]
Added to develop branch.

**Comment by eugenio412** [comment]
maybe something more specific would be nice, like a miminum Iv to trigger notification for each pokemon, rare pokemons tend to be wanted with 0 Iv, while common ones with higher IV

**Comment by Made123** [comment]
how about the moves into the IV notifications ?

**Comment by eugenio412** [comment]
@Made123 It's already there, maybe your phone is cutting the message, try rotating it and you will see it

**Comment by Made123** [comment]
I have tested, it works very well ! We can see clearly the notification on IOS and Android. I only have one request: have a IV filter list. Because per example, if i add the starters and snorlax into encounter list. I would like to notify the snorlax whatever its IV but add a filter for the starters. In this case, the filter IV list shall not be big because there are not much pokemons that we want to apply an IV filter.

What do you think about it.
To not disturb the normal operation, you can add a boolean true/false to use the filter IV list.

**Comment by Unknown66** [comment]
Good idea only question is per user or set by admin?

Empty list would be not using list and dont filter any.

**Comment by Made123** [comment]
By admin will be great.
And if you don't want the pokemon anymore, just Retire it from the classic list of notification.
Empty list = no filter.

**Comment by Unknown66** [comment]
If we do the list stuff I think individual IV for each pokemon would be fine.
The POKEMON_MINIMUM_IV is dropped then.

**Comment by Zentriert** [comment]
I would absolutely love the ability to filter IV per Pokemon because as others said, I want to get notified of all Snorlax, Magmar, etc, regardless of IV but only want to be notified of a good IV starter Pokemon. (because 98% of the starters seem to have under 40% average IVs ...)

Thank you for making this as awesome as it is!

**Comment by pki0** [comment]
> I would absolutely love the ability to filter IV per Pokemon because as others said, I want to get notified of all Snorlax, Magmar, etc, regardless of IV but only want to be notified of a good IV starter Pokemon. 

I'm doing this just running zwei Bots ;-)

But:
What about a bot command for setting minimum_iv per user?

**Comment by Zentriert** [comment]
Hmm I'm not sure how to run two bots like that, you mean two separate maps
and two separate telegram bots? PokeAlarm is looking like they're about to
start a new branch with this feature too.

**Comment by pki0** [comment]
You don't need a second Map. Just create a new Telegram Bot, copy the
folder, Insert the new bottoken and settings into the config and Start the second
bot in a new Terminal.

**Comment by Unknown66** [comment]
Okay current plan is the following:
Adding a global list with pokemonid and iv threshold. It's the same for all users.
Maybe later adding a user dependant list with the same stuff (If it's desired)

**Comment by Unknown66** [comment]
Added with commit c0fb035a7ad42136832bc10530478c04a0d2fcd8.
Wiki updated. See [here](https://github.com/eugenio412/PogomBOT/wiki/config-bot.json-setup#pokemon_min_iv_filter_list).

Post feedback please! :+1: 

PS: Sry for waiting that much time!

**Comment by Made123** [comment]
@Unknown66 yes will try in few hour !

**Comment by Unknown66** [comment]
@Made123 use latest version I fixed an annoying bug (no notifications)
